title: All types of “a”
email: david@rosettatype.com
description: >
  A collection of peculiar shapes of the Latin lowercase letter ‘a’ (U+0061), subjectively selected to illustrate that an essential form of ‘a’ (if it exists) must be quite complex.
url: https://all-types-of-a.rosettatype.com 
baseurl: ""
github_username: rosettatype

# Build settings
markdown: kramdown

# The default sharing image for sharing any page to social media. If a post has
# a "sharing_image" meta that will be used instead
# Use a relative path from the root of the project!
sharing_image: /assets/sharing_image.png